{"uuid": "778f72ac-26b5-4572-89e8-10ab60229c86", "children": ["7ba3db71-24e8-44ff-a44a-3a722650c328"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\venv\\Lib\\site-packages\\pluggy\\_callers.py\", line 80, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\QAGURU_hw_6_12\\test\\conftest.py\", line 46, in setup_browser\n    driver = webdriver.Remote(\n             ^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 272, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 364, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 429, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\Ekaterina.Torsunova\\PycharmProjects\\QAGURU_hw_6.12\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 207, in check_response\n    raise exception_class(value)\n"}, "start": 1691607049993, "stop": 1691607050413}], "start": 1691607049993, "stop": 1691607050735}